export const data = {
  loggedInUser: '',
  products: [
    {
      id: 1,
      price: "$36",
      disprice: "$24",
      imgsrc: "assets/images/trending-01.jpg",
      category: "adventure",
      title: "The Witcher 3",
    },
    {
      id: 2,
      price: "$36",
      disprice: "$24",
      imgsrc: "assets/images/trending-02.jpg",
      category: "adventure",
      title: "Horizon Zero Dawn",
    },
    {
      id: 3,
      price: "$36",
      disprice: "$24",
      imgsrc: "assets/images/trending-03.jpg",
      category: "role-playing",
      title: "Elden Ring",
    },
    {
      id: 4,
      price: "$36",
      disprice: "$24",
      imgsrc: "assets/images/trending-04.jpg",
      category: "strategy",
      title: "Age of Empires IV",
    },
    {
      id: 5,
      price: "$36",
      disprice: "$24",
      imgsrc: "assets/images/trending-01.jpg",
      category: "shooter",
      title: "Call of Duty",
    },
    {
      id: 6,
      price: "$36",
      disprice: "$24",
      imgsrc: "assets/images/trending-02.jpg",
      category: "sports",
      title: "FIFA 22",
    },
    {
      id: 7,
      price: "$36",
      disprice: "$24",
      imgsrc: "assets/images/trending-03.jpg",
      category: "role-playing",
      title: "Cyberpunk 2077",
    },
    {
      id: 8,
      price: "$36",
      disprice: "$24",
      imgsrc: "assets/images/trending-04.jpg",
      category: "strategy",
      title: "StarCraft II",
    },
    {
      id: 9,
      price: "$36",
      disprice: "$24",
      imgsrc: "assets/images/trending-01.jpg",
      category: "simulation",
      title: "The Sims 4",
    },
    {
      id: 10,
      price: "$36",
      disprice: "$24",
      imgsrc: "assets/images/trending-02.jpg",
      category: "racing",
      title: "Forza Horizon 5",
    },
    {
      id: 11,
      price: "$36",
      disprice: "$24",
      imgsrc: "assets/images/trending-03.jpg",
      category: "adventure",
      title: "Red Dead Redemption 2",
    },
    {
      id: 12,
      price: "$36",
      disprice: "$24",
      imgsrc: "assets/images/trending-04.jpg",
      category: "action",
      title: "Ghost of Tsushima",
    },
  ],
  users: [],
};
